(******************************************************************************)
(*                                                                            *)
(*                    Gellar Field: Warp Transit Integrity                    *)
(*                                                                            *)
(*     Formalizes Gellar field protection during Immaterium transit: field    *)
(*     states (active/flickering/collapsed), daemonic incursion predicates,   *)
(*     power consumption rates, and Navigator dependency. Proves field        *)
(*     collapse implies crew corruption probability approaches unity.         *)
(*                                                                            *)
(*     "The Warp is a strange and terrible place. You might as well try to    *)
(*     understand the malevolence of the universe."                           *)
(*     - Erta Doloreza, Rogue Trader, M.39                                    *)
(*                                                                            *)
(*     Author: Charles C. Norton                                              *)
(*     Date: January 7, 2026                                                  *)
(*     License: MIT                                                           *)
(*                                                                            *)
(******************************************************************************)
